### ISSUE TITLE
Building on Ubuntu?

### ISSUE THREAD

**Issue by Jestre** [sub7zero/OpusFeed#1]
Found this tonight, and tried to build it on a new Ubuntu 16.04.1 server.  Installed the prereqs:

$ sudo apt-get install build-essential cmake yasm

Then did:

$ make init
$ make 3rdparty

This fails when it gets to the libav section with:

cd /root/OpusFeed/tmp/libav* && mv -f ./libavformat/oggenc.patched ./libavformat/oggenc.c
cd /root/OpusFeed/tmp/libav* && ./configure --prefix=/root/OpusFeed/3rdparty --disable-programs --disable-network --enable-gpl --enable-nonfree --enable-libopus 2>&1 | tee /root/OpusFeed/logs/libav.txt
ERROR: opus not found

Any ideas?  Is there a preferred OS for this application?

**Comment by sub7zero** [comment]
you might wanna check './logs/opus.txt' to see if opus was built correctly.
as for a preferred OS, it should work just fine on both windows & linux

**Comment by Jestre** [comment]
My fault.  I thought pkg-config was installed as part of build-essential, but apparently not.  The error in the opus.txt file didn't seem to point in that direction, but after installing pkg-config all built successfully.  I ran it against one of the podcasts I listen to and all worked as expected.  

Sorry for the interruption.
