### ISSUE TITLE
RSS Not updated

### ISSUE THREAD

**Issue by Jestre** [sub7zero/OpusFeed#2]
Now that I got this working, I created all of the output for a test podcast, and on initial run everything worked as expected.  After waiting a week or so, I re-ran the process, and it properly downloaded and converted the new audio file and appears to have rewritten the output RSS feed (it update the feed's pubDate and lastBuildDate), but it did not add the new data to the feed. 

I have told it to only use 5 episodes, so it also appears to have deleted the oldest audio.  Do I need to do something else to get it to add the entry to the output feed?

Here is the command I am using:

    root@opus:~# cat cmd.sh
    #!/bin/bash
    
    OpusFeed/bin/opusfeed \
	--media-dir /var/www/html/funko/media \
	--feed-url http://gofunkoyourself.libsyn.com/rss \
	--media-prefix media \
	--db-file /var/www/html/funko/funko.db \
	--output-rss /var/www/html/funko/funko.rss \
	--update-interval 0 \
	--max-items 5

The plan is to then process the output feed with a simple Python script to create websites a la the NA Opus Feed.

Any ideas?

For reference, here is the output:

    root@opus:~# ./cmd.sh
    + opening database
    + cleaning up orphan files
    + fetching feed
    > (82.6 KB-82.6 KB) 100% @ 778.7 KB/s - 00:00:00 , ETA : 00:00:00
    + [1] new item(s), [2] updated item(s)
    + downloading (Lost, Ren & Stimpy, Naruto, South Park, Fantastic Beasts and Where to Find them, and more!)
    > (33.0 MB-33.0 MB) 100% @ 78.5 MB/s - 00:00:00 , ETA : 00:00:00
    + converting (Lost, Ren & Stimpy, Naruto, South Park, Fantastic Beasts and Where to Find them, and more!)
    > (00:36:06-00:36:05~) 100%
    + cleaning up outdated items
    + generating rss feed

**Comment by sub7zero** [comment]
can't say without the db file...anywayS, in a day or two I'll push version 1.4 with some major changes and additional options. try it and keep me posted.
